Repository Trisha-tech/OnlineBookSales, pull requests merged in 2024-10, with the labels that each got.

#275 Added docker compose file
  docker-compose.yml
Labels: enhancement, level2, gssoc-ext

#301 Enhanced errorHandling and responseHandling.
  controllers/adminController.js
  controllers/customerController.js
  controllers/orderController.js
  controllers/productController.js
  utils/errorHandler.js
  utils/responseHandler.js
Labels: enhancement, level3, gssoc-ext

#292 Readme file Issue Updation
  README.md
Labels: enhancement, level1, gssoc-ext

#288 Added the backend part for Google Sign IN
  .env.sample
  client/src/App.js
  client/src/server.js
  models/customerSchema.js
  package-lock.json
  package.json
Labels: enhancement, level3, gssoc-ext

#268 added sorting options in order page
  client/src/Pages/Orders.jsx
Labels: bug, level2, gssoc-ext

#264 Cart Status update when user is not logged in #256
  client/src/Components/NavBar/NavBar.jsx
  client/src/Pages/Cart.jsx
Labels: bug, level2, gssoc-ext

#296 Signup ui updated
  client/src/Pages/LoginPage.jsx
  client/src/Pages/SignUpPage.jsx
Labels: enhancement, level2, gssoc-ext

#308 Adds functionality to align the **Login** and **Theme Switcher** buttons to the right #304
  client/src/Components/NavBar/NavBar.jsx
Labels: enhancement, level1, gssoc-ext

#291 login-ui-updated
  client/src/Pages/LoginPage.jsx
Labels: enhancement, level2, gssoc-ext

#311 Enhanced the Faq section
  client/src/Pages/Faq.jsx
Labels: bug, level1, gssoc-ext

#325 Dark Theme of Website Updated Issue no #290 Resolved
  client/src/App.js
  client/src/Components/Footer/Footer.jsx
  client/src/Components/NavBar/NavBar.jsx
  client/src/Pages/Cart.jsx
Labels: enhancement, level1, gssoc-ext

#310 Integration of Chatbot (#306)
  client/public/index.html
Labels: enhancement, level3, gssoc-ext

#282 Issue #259 - Added routes for each categories in the Book Categories section and created blank pages for each of the pages
  client/src/App.js
  client/src/Pages/ActionPage.jsx
  client/src/Pages/FictionPage.jsx
  client/src/Pages/Home.jsx
  client/src/Pages/MangaPage.jsx
  client/src/Pages/PhilosophyPage.jsx
  client/src/Pages/RomancePage.jsx
  client/src/Pages/TechPage.jsx
  client/src/Pages/ThrillerPage.jsx
  package-lock.json
  package.json
Labels: good first issue, level1, gssoc-ext

#323 new arrival and review section added : I have done the issue that is assigned to me #271 done
  client/package-lock.json
  client/package.json
  client/src/Pages/BannerCard.css
  client/src/Pages/BannerCard.js
  client/src/Pages/Home.jsx
  client/src/Pages/Newarrivals.js
  client/src/Pages/Review.jsx
  client/src/assets/image/profile.jpg
Labels: enhancement, level2, gssoc-ext

#337 Added the Confirm Password Field to the Sign Up Page
  client/src/Pages/SignUpPage.jsx
Labels: enhancement, level1, gssoc-ext

#363 Update readme
  PROJECT_DETAILS.md
  README.md
  cover-page.png
Labels: enhancement, level2, gssoc-ext

#396 Google signin (frontend)
  client/src/Components/GoogleLogin.jsx
  client/src/Pages/LoginPage.jsx
  client/src/Pages/SignUpPage.jsx
  client/src/assets/google_icon.jpg
Labels: enhancement, level2, gssoc-ext

#390 [Bug]: Fix the Register and Signup Issues
  .env.sample
  client/src/server.js
Labels: bug, level2, gssoc-ext

#376 Improved search Input button
  client/src/Components/SearchBar.js
  client/src/Pages/Home.jsx
Labels: enhancement, level2, gssoc-ext

#355 ADDED BOOKS AUTHORS PRICE
  .vscode/settings.json
  client/public/action.html
  client/public/fiction.html
  client/public/index.html
  client/public/manga.html
  client/public/philosophy.html
  client/public/quiz.html
  client/public/tech.html
  client/public/thriller.html
  index.js
Labels: enhancement, level2, gssoc-ext

#398 added not found page
  client/src/App.js
  client/src/Pages/NotFound.jsx
Labels: enhancement, level2, gssoc-ext, hacktoberfest-accepted

#404 Add Multilingual Translator to OnlineBookSales Application
  client/public/google.png
  client/src/Components/Footer/Footer.jsx
  client/src/Components/GoogleTranslate.jsx
Labels: enhancement, level2, gssoc-ext

#425 chatbot added and its working!✨
  client/public/index.html
  client/src/App.js
  client/src/chatbot.jsx
Labels: enhancement, level2, gssoc-ext

#432 add box shadow and hover effect
  client/public/action.html
  client/public/books.html
  client/public/fiction.html
  client/public/manga.html
  client/public/philosophy.html
  client/public/quiz.html
  client/public/tech.html
  client/public/thriller.html
  client/src/Components/index.js
Labels: enhancement, level1, gssoc-ext, hacktoberfest

#446 improved navbar for mobile
  client/src/Components/NavBar/NavBar.jsx
Labels: bug, level1, gssoc-ext

#440 Improving Trending Books and Book Categories section
  client/src/Pages/Home.jsx
  client/src/assets/image/Dune.jpg
  client/src/assets/image/WhereTheCrawdadsSings.jpg
  client/src/assets/image/klaraAndtheSun.jpg
  client/src/assets/image/malibuRising.jpg
  client/src/assets/image/projectHailMary.jpg
  client/src/assets/image/theMidnightLibrary.jpg
  client/src/assets/image/theVanishingHalf.jpg
  package-lock.json
Labels: enhancement, level2, gssoc-ext

#380 Issue#283 - User authentication (Sign up) successful
  .gitignore
  controllers/customerController.js
  index.js
Labels: bug, level2, gssoc-ext

#388 Added AI-BookRecommdation component
  client/src/Components/AI-BookRecommdation/.gitignore
  client/src/Components/AI-BookRecommdation/PREREQUISITES.md
  client/src/Components/AI-BookRecommdation/README.md
  client/src/Components/AI-BookRecommdation/main.py
  client/src/Components/AI-BookRecommdation/requirements.txt
  client/src/Components/AI-BookRecommdation/sample.config.toml
Labels: enhancement, level3, gssoc-ext

#477 chnage the colour of scroll bar
  client/src/Components/index.js
  client/src/index.css
Labels: enhancement, level1, gssoc-ext

#482 Update cors origin configuration #473
  index.js
Labels: bug, level1, gssoc-ext, hacktoberfest-accepted

#481 Update social icons' hover colors to reflect original brand colors
  client/src/Components/Footer/Footer.jsx
  package-lock.json
Labels: enhancement, level1, gssoc-ext, hacktoberfest-accepted

#497 fix: commented all the unused variables
  client/src/App.js
  client/src/Components/CustomerProfile/Sidebar.jsx
  client/src/Pages/Cart.jsx
  client/src/Pages/LoginPage.jsx
  client/src/Pages/Orders.jsx
  client/src/Pages/ProductItem.js
  client/src/Pages/SignUpPage.jsx
  client/src/Pages/Wishlist.jsx
  client/src/assets/Logo.png
Labels: bug, level1, gssoc-ext, hacktoberfest-accepted

#502 Enhances With Best Code Practices, Code Style Guidelines And Acknowledgments
  CONTRIBUTING.md
Labels: documentation, level1, gssoc-ext, hacktoberfest-accepted

#562 [Feature Request]: Implemented Google Books API on search bar
  client/src/Components/NavBar/NavBar.jsx
  client/src/Components/SearchBar.js
  client/src/Pages/Home.jsx
Labels: enhancement, level2, gssoc-ext

#553 [Bug]: fixed the issue of text in faq page #550
  client/src/Pages/Faq.jsx
Labels: bug, level1, gssoc-ext

#539 added cancel and returns page
  client/src/App.js
  client/src/Components/Footer/Footer.jsx
  client/src/Pages/CancelReturns.jsx
Labels: enhancement, level1, gssoc-ext, hacktoberfest-accepted

#535 [Feature] : Added validation for form inputs
  client/package-lock.json
  client/package.json
  client/src/Pages/LoginPage.jsx
  client/src/Pages/SignUpPage.jsx
  client/src/validations/validation.js
  package-lock.json
  package.json
Labels: enhancement, level1, gssoc-ext, hacktoberfest-accepted

#571 [Bug Fix] Fixed issue #542
  client/src/Pages/Wishlist.jsx
Labels: bug, level1, gssoc-ext, hacktoberfest-accepted

#573 Generate random books using Google books api in New arrivals
  client/src/Pages/Newarrivals.js
Labels: enhancement, level2, gssoc-ext

#588 Updated CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation, enhancement, level1, gssoc-ext

#592 added troubleshooting section to the readme file
  README.md
Labels: documentation, enhancement, level1, gssoc-ext

#597 Added book info page
  client/src/App.js
  client/src/Pages/Book.css
  client/src/Pages/Book.jsx
  client/src/Pages/Newarrivals.js
Labels: enhancement, level2, gssoc-ext

#604 [Fix]: removed underline Properties
  client/src/Components/NavBar/NavBar.jsx
Labels: bug, level1, gssoc-ext, hacktoberfest-accepted

#605 [Fix]: fixes subscribe button
  client/src/Components/Footer/Footer.css
Labels: bug, level1, gssoc-ext, hacktoberfest-accepted

#568 Progressbar implemented
  client/src/Components/NavBar/NavBar.jsx
  client/src/Components/NavBar/ScrollProgressBar.jsx
  client/src/components/Header/Header.js
Labels: enhancement, level2, gssoc-ext, hacktoberfest-accepted

#582 background color changed of the toggle button
  client/public/index.html
  client/src/index.css
Labels: bug, level1, gssoc-ext

#587 Enhanced Functionality and Styling of Cart Page
  client/public/cart.webp
  client/public/error.png
  client/src/Components/NavBar/NavBar.jsx
  client/src/Pages/Cart.css
  client/src/Pages/Cart.jsx
  client/src/index.js
Labels: enhancement, level2, gssoc-ext, hacktoberfest-accepted

#642 Auto label workflow automation🚀
  .github/workflows/auto-label.yml
Labels: level2, gssoc-ext, hacktoberfest-accepted

#563 Customer profile UI
  .gitignore
  client/package-lock.json
  client/src/Pages/CustomerProfile.jsx
  client/src/assets/Giftcard.jpg
  client/src/components/AI-BookRecommdation/.gitignore
  client/src/components/AI-BookRecommdation/PREREQUISITES.md
  client/src/components/AI-BookRecommdation/README.md
  client/src/components/AI-BookRecommdation/main.py
  client/src/components/AI-BookRecommdation/requirements.txt
  client/src/components/AI-BookRecommdation/sample.config.toml
  client/src/components/Card/Book.jsx
  client/src/components/Card/ProductCard.css
  client/src/components/Card/ProductCard.jsx
  client/src/components/CustomerProfile/CorporateRequirements.jsx
  client/src/components/CustomerProfile/DeliveryLocation.jsx
  client/src/components/CustomerProfile/Giftcard.jsx
  client/src/components/CustomerProfile/Orders.jsx
  client/src/components/CustomerProfile/Pancard.jsx
  client/src/components/CustomerProfile/Profile.jsx
  client/src/components/CustomerProfile/Sidebar.jsx
  client/src/components/Footer/Footer.css
  client/src/components/Footer/Footer.jsx
  client/src/components/GoToTop.jsx
  client/src/components/GoogleLogin.jsx
  client/src/components/GoogleTranslate.jsx
  client/src/components/NavBar/NavBar.jsx
  client/src/components/NavBar/ScrollProgressBar.jsx
  client/src/components/Preloader.css
  client/src/components/Preloader.jsx
  client/src/components/Product.jsx
  client/src/components/SearchBar.js
  client/src/components/Searchbar.css
  client/src/components/Trending.jsx
  client/src/components/index.js
  client/src/components/temp.js
  index.js
  package-lock.json
Labels: bug, level2, gssoc-ext, hacktoberfest-accepted
