Repository Trisha-tech/OnlineBookSales, pull requests merged in 2024-08, with the labels that each got.

#219 Corrected all the errors
  client/src/App.js
  client/src/Pages/Orders.jsx
  client/src/Pages/Wishlist.jsx
Labels: level2, gssoc

#226 Fixed Dark Mode Issue in Login and Signup Page
  client/src/App.js
  client/src/Components/SearchBar.js
  client/src/Pages/LoginPage.jsx
  client/src/Pages/SignUpPage.jsx
  client/src/index.js
  client/tailwind.config.js
Labels: level2, gssoc

#223 Added A "Preloader" Matching to Website Books Theme
  client/public/preload.mp4
  client/src/App.js
  client/src/Components/Preloader.css
  client/src/Components/Preloader.jsx
  client/src/Pages/AboutUs.jsx
  client/src/Pages/Cart.jsx
  client/src/Pages/Contact.jsx
  client/src/Pages/Faq.jsx
  client/src/Pages/Home.jsx
  client/src/Pages/LoginPage.jsx
  client/src/Pages/Orders.jsx
  client/src/Pages/Shop.jsx
  client/src/Pages/SignUpPage.jsx
  client/src/Pages/Wishlist.jsx
Labels: level2, gssoc

#231 Added Trail Effect to the Cursor for the Website
  client/public/index.html
Labels: level2, gssoc

#230 Fixed Order Page Frontend UI
  client/src/Pages/Orders.jsx
Labels: level2, gssoc

#234 Enhanced The "Footer" Section. Added "Legal" Section and "Dynamic Copyright" Section
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/Components/Footer/Footer.css
  client/src/Components/Footer/Footer.jsx
  client/src/Pages/PrivacyPolicy.jsx
  client/src/index.css
Labels: level3

#247 Added "Scroll to Top" Button Functionality
  client/src/App.js
  client/src/Components/GoToTop.jsx
Labels: level1, gssoc

#244 Created Terms and Conditions Page For the Website
  client/src/App.js
  client/src/Components/Footer/Footer.jsx
  client/src/Pages/Terms.jsx
Labels: level2, gssoc

#248 Design A New "Logo" and A "Favicon" for The Website
  client/public/favicon.ico
  client/public/index.html
  client/src/Components/NavBar/NavBar.jsx
  client/src/assets/Logo.png
Labels: level2, gssoc

#243 Made Contact Us Page Fully Responsive
  client/src/Pages/Contact.jsx
Labels: level1, gssoc

#242 Enhanced Vertical Scrollbar to Match Website Design Theme
  client/src/index.css
Labels: level1, gssoc

#254 Creade Licensing Page to the Website
  client/src/App.js
  client/src/Components/Footer/Footer.jsx
  client/src/Pages/Licensing.jsx
Labels: level2, gssoc

#252 Create "Our Contributors" Page for the website
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/Components/Footer/Footer.jsx
  client/src/Pages/Contributors.css
  client/src/Pages/Contributors.jsx
Labels: level2, gssoc
