Repository Trisha-tech/OnlineBookSales, pull requests merged in 2024-06, with the labels that each got.

#40 Revert "added searchProduct and filterProduct controllers in product …
  controllers/customerController.js
  models/productSchema.js
  package-lock.json
Labels: level2, gssoc

#161 frontend connectivity
  .env.sample
  client/package-lock.json
  index.js
  package-lock.json
  package.json
Labels: level2, gssoc

#156 Added an Eye icon to the Password field
  client/src/Pages/LoginPage.jsx
Labels: level1, gssoc

#166 Create LICENSE
  LICENSE
Labels: level2, gssoc

#168 error 404
  client/public/404.html
  client/public/script.js
  client/public/styles.css
Labels: level1, gssoc

#169 Added the contact us page
  client/src/App.js
  client/src/Components/Footer/Footer.jsx
  client/src/Pages/Contact.jsx
Labels: level1, gssoc

#172 Implement greeting message upon issue closure
  .github/workflows/autocomment-iss-close.yml
Labels: level1, gssoc

#170 Shop page frontend+backend
  client/package-lock.json
  client/package.json
  client/src/Pages/ProductItem.js
  client/src/Pages/Shop.jsx
  index.js
  package-lock.json
  package.json
Labels: level2, gssoc

#183 Pre loader component
  client/src/Pages/Cart.jsx
  client/src/Pages/Home.jsx
  client/src/Pages/Orders.jsx
  client/src/Pages/ProductItem.js
  client/src/Pages/Spinner.js
  client/src/Pages/Wishlist.jsx
  client/src/Pages/preLoader.gif
  index.js
  package.json
Labels: level1, gssoc

#182 Add Dark Mode Feature
  client/src/App.js
  client/src/Components/NavBar/NavBar.jsx
  client/src/assets/moon.png
  client/src/assets/sun.png
Labels: level2, gssoc

#185 Adding Featured Author section
  client/src/Pages/Home.jsx
Labels: level2, gssoc

#187 Wishlist component
  client/package-lock.json
  client/package.json
  client/src/Pages/ProductItem.js
  client/src/Pages/Wishlist.jsx
  controllers/customerController.js
  index.js
  middlewares/auth.js
  models/wishlistSchema.js
  routes/wishlistRoutes.js
Labels: level2, gssoc

#191 component SearchBar.js continuation-
  client/src/Components/SearchBar.js
Labels: level1, gssoc

#190 Add a search bar- home.jsx
  client/src/Pages/Home.jsx
Labels: level1, gssoc

#194 INTRODUCING REAL-TIME ORDER TRACKING: SEAMLESSLY MONITOR YOUR ORDER S…
  client/src/Pages/Orders.jsx
Labels: level3, gssoc
