Repository Trisha-tech/OnlineBookSales, pull requests merged in 2024-07, with the labels that each got.

#198 Added CART Page [frontend + backend]
  client/src/Pages/Cart.css
  client/src/Pages/Cart.jsx
  client/src/Pages/Home.jsx
  client/src/Pages/Spinner.jsx
  client/src/api/api.js
  client/src/assets/image/author1.jpeg
  index.js
  package-lock.json
  package.json
  routes/cartRoutes.js
Labels: level3, gssoc

#203 feature access and refresh token add
  .env.sample
  controllers/customerController.js
  models/customerSchema.js
Labels: level2, gssoc

#208 Added the faq page
  client/src/App.js
  client/src/Components/Footer/Footer.jsx
  client/src/Pages/Faq.jsx
Labels: level2, gssoc

#206 Added the wishlist section(both frontend + backend)
  client/src/Components/NavBar/NavBar.jsx
  client/src/Pages/Orders.jsx
  client/src/Pages/Wishlist.css
  client/src/Pages/Wishlist.jsx
  client/src/server.js
  package-lock.json
  package.json
Labels: level2, gssoc

#205 Added home in navbar redirecting to home
  client/src/Pages/Orders.jsx
Labels: level1, gssoc
